# Generated by Django 5.2.5 on 2025-08-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'faq', 'verbose_name_plural': 'faqs'},
        ),
    ]
