# Generated by Django 5.2.5 on 2025-08-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
    ]
